attach(iris)
layout(matrix(c(1, 1, 2, 2, 1, 1, 3, 4, 5, 5, 3, 4, 5, 5, 6, 6), 4, 4, byrow = TRUE))
pdf("E:\\ProgrammingProjects\\RStudioProjects\\Data_Science\\Lecture2_DataOperation\\mytest.pdf")
boxplot(iris$Sepal.Length~iris$Species, col = terrain.colors(3))
plot(iris$Sepal.Length, iris$Sepal.Width, main = "Sepal Length vs. Sepal Width")
hist(iris$Sepal.Width)
plot(iris$Petal.Length, iris$Petal.Width)
boxplot(iris$Species~iris$Sepal.Length)
hist(iris$Sepal.Length)
dev.off()
